const fs = require('fs');
const path = require('path');

const SOURCE_URLS = [
  process.env.NIFTY50_SOURCE_URL,
  'https://www.nseindia.com/content/indices/ind_nifty50list.csv',
  'https://niftyindices.com/IndexConstituent/ind_nifty50list.csv',
  'https://raw.githubusercontent.com/datasets/nifty-50/master/data/nifty-50.csv',
].filter(Boolean);
const OUTPUT_PATH = path.resolve('src', 'lib', 'tickers.js');

function parseCsvLine(line) {
  const result = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }
    if (ch === ',' && !inQuotes) {
      result.push(current);
      current = '';
      continue;
    }
    current += ch;
  }
  result.push(current);
  return result.map((value) => value.trim());
}

function escapeString(value) {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

async function fetchCsv(url) {
  const resp = await fetch(url, {
    headers: {
      'User-Agent': 'Mozilla/5.0',
      Accept: 'text/csv',
    },
  });
  if (!resp.ok) {
    throw new Error(`Failed to fetch: ${url} (${resp.status})`);
  }
  return resp.text();
}

function buildTickers(csvText) {
  const lines = csvText.split(/\r?\n/).filter(Boolean);
  if (lines.length < 2) {
    throw new Error('CSV did not contain enough rows.');
  }
  const header = parseCsvLine(lines[0]);
  const symbolIdx = header.findIndex((value) => value.toLowerCase().includes('symbol'));
  const nameIdx = header.findIndex((value) => value.toLowerCase().includes('company') || value.toLowerCase().includes('name'));
  if (symbolIdx < 0 || nameIdx < 0) {
    throw new Error(`CSV header missing Symbol/Company columns: ${header.join(', ')}`);
  }
  const items = [];
  for (const line of lines.slice(1)) {
    const row = parseCsvLine(line);
    if (!row[symbolIdx] || !row[nameIdx]) continue;
    items.push({
      symbol: row[symbolIdx],
      name: row[nameIdx],
    });
  }
  if (!items.length) {
    throw new Error('No tickers parsed from CSV.');
  }
  items.sort((a, b) => a.symbol.localeCompare(b.symbol));
  return items;
}

function writeTickers(items, sourceUrl) {
  const lines = [];
  lines.push('// AUTO-GENERATED by scripts/update_nifty50.cjs');
  lines.push(`// Source: ${sourceUrl}`);
  lines.push('export const TICKERS = [');
  for (const item of items) {
    lines.push(`  { symbol: '${escapeString(item.symbol)}', name: '${escapeString(item.name)}' },`);
  }
  lines.push('];');
  fs.writeFileSync(OUTPUT_PATH, lines.join('\n') + '\n', 'utf8');
}

async function main() {
  let lastError = null;
  for (const url of SOURCE_URLS) {
    try {
      const csv = await fetchCsv(url);
      const items = buildTickers(csv);
      writeTickers(items, url);
      console.log(`Updated ${items.length} tickers -> ${OUTPUT_PATH}`);
      return;
    } catch (error) {
      lastError = error;
    }
  }
  if (lastError) {
    console.warn('Unable to update tickers automatically.');
    console.warn('Set NIFTY50_SOURCE_URL to a CSV source and retry.');
    console.warn(lastError.message);
  }
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
