// Plain-English explanation generated by the LLM
export default function ExplanationPanel({ explanation, source, onExplain, loading, disabled }) {
  return (
    <div className="card" style={{ display: 'grid', gap: 10 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div className="mono" style={{ fontSize: 10, letterSpacing: '0.12em', color: 'var(--text-muted)' }}>
          LLM EXPLANATION
        </div>
        {onExplain && (
          <button
            type="button"
            className="panel-button"
            onClick={onExplain}
            disabled={disabled || loading}
          >
            {loading ? 'GENERATING...' : 'GENERATE'}
          </button>
        )}
      </div>
      {source && (
        <div className="mono" style={{ fontSize: 9, letterSpacing: '0.12em', color: 'var(--text-muted)' }}>
          SOURCE: {source.toUpperCase()}
        </div>
      )}
      {explanation ? (
        <div style={{ lineHeight: 1.6 }}>{explanation}</div>
      ) : (
        <div style={{ color: 'var(--text-muted)' }}>No explanation returned yet.</div>
      )}
    </div>
  );
}
