// Plain-English explanation generated by the LLM
export default function ExplanationPanel({ explanation }) {
  return (
    <div className="card" style={{ display: 'grid', gap: 10 }}>
      <div className="mono" style={{ fontSize: 10, letterSpacing: '0.12em', color: 'var(--text-muted)' }}>
        LLM EXPLANATION
      </div>
      {explanation ? (
        <div style={{ lineHeight: 1.6 }}>{explanation}</div>
      ) : (
        <div style={{ color: 'var(--text-muted)' }}>No explanation returned yet.</div>
      )}
    </div>
  );
}
